baseURL = ""
languageCode = "en-us"
title = "Teo Boy"
theme = "hallo"

[Author]
    name = "Teo"

[params]
    [params.colors]
        background = "#6166ff"
        foreground = "#edf7ff"
        hover = "#ffba82"

    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/tullbo/teoboy"

    [[params.links]]
        icon = "youtube"
        title = "Youtube"
        url = "https://youtu.be/gxpT2rTyXXg"
